apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod

resources:
- ../../base
- configmap.yaml

images:
- name: nginx
  newName: public.ecr.aws/nginx/nginx
  newTag: "1.25"

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 32052
  target:
    kind: Service
    name: kargo-test
labels:
- includeSelectors: true
  pairs:
    app: kargo-test-prod
