apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

nameSuffix: -prod_dc1

patches:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: kargo-test
        namespace: argocd
        annotations:
          kargo.akuity.io/authorized-stage: kargo-test:prod_dc1
      spec:
        source:
          path: k8s/rendered/prod_dc1
