apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-test-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>prod-dc1</title>
    </head>
    <body>

    <h1>prod-dc1</h1>

    </body>
    </html>