apiVersion: v1
kind: Namespace
metadata:
  name: kargo-test
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-test
  namespace: kargo-test
spec:
  subscriptions:
    - image:
        repoURL: public.ecr.aws/nginx/nginx
        imageSelectionStrategy: Digest
        constraint: stable
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-test
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-test
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            checkout:
              - branch: main
                path: src
        - uses: kustomize-set-image
          config:
            path: src/k8s/overlays/dev
        - uses: git-commit
          as: commit
          config:
            path: src
            message: "Update image tag for dev"
        - uses: git-push
          as: gitPush
          config:
            generateTargetBranch: true
            path: src
        - uses: git-open-pr
          as: openPr
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            sourceBranch: ${{ outputs.gitPush.branch }} # Note: branch dynamically generated by git-push
            targetBranch: main
            title: "Promote Freight ${{ ctx.targetFreight.name }} to dev"
        - uses: git-wait-for-pr
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            prNumber: ${{ outputs.openPr.pr.id }}
        - uses: argocd-update
          config:
            apps:
              - name: kargo-test-dev
                namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-test
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-test
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            checkout:
              - branch: main
                path: src
        - uses: kustomize-set-image
          config:
            path: src/k8s/overlays/test
        - uses: git-commit
          as: commit
          config:
            path: src
            message: "Update image tag for test"
        - uses: git-push
          as: gitPush
          config:
            generateTargetBranch: true
            path: src
        - uses: git-open-pr
          as: openPr
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            sourceBranch: ${{ outputs.gitPush.branch }} # Or whatever git-push outputs
            targetBranch: main
            title: "Promote Freight ${{ ctx.targetFreight.name }} to test"
        - uses: git-wait-for-pr
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            prNumber: ${{ outputs.openPr.pr.id }}
        - uses: argocd-update
          config:
            apps:
              - name: kargo-test-test
                namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod_dc1
  namespace: kargo-test
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-test
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            checkout:
              - branch: main
                path: src
        - uses: kustomize-set-image
          config:
            path: src/k8s/overlays/prod_dc1
        - uses: git-commit
          as: commit
          config:
            path: src
            message: "Update image tag for prod_dc1"
        - uses: git-push
          as: gitPush
          config:
            generateTargetBranch: true
            path: src
        - uses: git-open-pr
          as: openPr
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            sourceBranch: ${{ outputs.gitPush.branch }}
            targetBranch: main
            title: "Promote Freight ${{ ctx.targetFreight.name }} to prod_dc1"
        - uses: git-wait-for-pr
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            prNumber: ${{ outputs.openPr.pr.id }}
        - uses: argocd-update
          config:
            apps:
              - name: kargo-test-prod_dc1
                namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod_dc2
  namespace: kargo-test
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-test
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            checkout:
              - branch: main
                path: src
        - uses: kustomize-set-image
          config:
            path: src/k8s/overlays/prod_dc2
        - uses: git-commit
          as: commit
          config:
            path: src
            message: "Update image tag for prod_dc2"
        - uses: git-push
          as: gitPush
          config:
            generateTargetBranch: true
            path: src
        - uses: git-open-pr
          as: openPr
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            sourceBranch: ${{ outputs.gitPush.branch }}
            targetBranch: main
            title: "Promote Freight ${{ ctx.targetFreight.name }} to prod_dc2"
        - uses: git-wait-for-pr
          config:
            repoURL: https://github.com/frankc-cerebras/kargo-test.git
            prNumber: ${{ outputs.openPr.pr.id }}
        - uses: argocd-update
          config:
            apps:
              - name: kargo-test-prod_dc2
                namespace: argocd