apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-test-repo
  namespace: kargo-test
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<your-github-username>/kargo-test.git
  username: <your-github-username>
  password: <your-github-token>