apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/frankc-cerebras/kargo-test
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
